### PR TITLE
Add Python 3 support to srcbindiff.py

### PR DESCRIPTION
**Pull request by thestr4ng3r**
I used the zlib example from the readme to compare the following scenarios: Before these changes with Python 2, after these changes with Python 2 and after these changes with Python 3.
Both Python 2 cases gave the exact same sqlite database.
Python 3 was different, but there seem to be only differences in how ids are assigned, as well as the order of elements in JSON, which is probably because of changes in the implementations of set and dict.

The only changes I am not 100% sure about yet are these two:
https://github.com/joxeankoret/pigaios/pull/29/files#diff-896ceb413e77f27a034b3e24c53ab2c2R389
https://github.com/joxeankoret/pigaios/pull/29/files#diff-02b63b7451c485af3b9682e4c0059d6cR105
Why are you opening these files in binary mode? Both the source and the project file are text files, so this doesn't make much sense to me. In Python 3 this makes a difference because of str vs. bytes.

### CODE REVIEW

**Comment by joxeankoret** [comment]
Thanks! I will review and test it.

**Comment by XVilka** [comment]
Isn't it a good time for that change?

**Comment by joxeankoret** [comment]
I'm working on the port, actually.

**Comment by thestr4ng3r** [comment]
Of course it is more complex, this here is only for srcbindiff.py

**Pull request closed without merging**
